language: node_js
node_js:
    - "0.12.7"

sudo: false

addons:
  apt:
    packages:
      - xvfb

install:
  - npm install electron-prebuilt
  - npm install electron-mocha -g
  - npm install gulp -g
  - gulp
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - electron-mocha --renderer ./tests
