language: node_js
node_js:
    - "4.4.5"

os:
  - linux

sudo: false

addons:
  apt:
    packages:
      - xvfb

install:
  - npm install electron-mocha -g
  - npm install
  - npm install gulp -g
#  - cd src && gulp
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - electron-mocha --renderer ./tests
